package orb.corba;


/**
* orb/corba/RmiDatabaseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from orb/corba2/RmiDatabase.idl
* Monday, October 30, 2017 at 5:28:05 PM Eastern European Standard Time
*/

public interface RmiDatabaseOperations 
{
  String getName ();
  String getTableNames ();
  String getTable (String arg0);
  String subtract (String arg0, String arg1);
} // interface RmiDatabaseOperations
