package orb.corba;


/**
* orb/corba/RmiDatabaseHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from orb/corba2/RmiDatabase.idl
* Monday, October 30, 2017 at 5:28:05 PM Eastern European Standard Time
*/

abstract public class RmiDatabaseHelper
{
  private static String  _id = "RMI:orb.corba.RmiDatabase:0000000000000000";

  public static void insert (org.omg.CORBA.Any a, orb.corba.RmiDatabase that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static orb.corba.RmiDatabase extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (orb.corba.RmiDatabaseHelper.id (), "RmiDatabase");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static orb.corba.RmiDatabase read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_RmiDatabaseStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, orb.corba.RmiDatabase value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static orb.corba.RmiDatabase narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof orb.corba.RmiDatabase)
      return (orb.corba.RmiDatabase)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      orb.corba._RmiDatabaseStub stub = new orb.corba._RmiDatabaseStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static orb.corba.RmiDatabase unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof orb.corba.RmiDatabase)
      return (orb.corba.RmiDatabase)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      orb.corba._RmiDatabaseStub stub = new orb.corba._RmiDatabaseStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
