package orb.corba;

/**
* orb/corba/RmiDatabaseHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from orb/corba/RmiDatabase.idl
* 28 ������� 2017 �. 15:49:48 EEST
*/

public final class RmiDatabaseHolder implements org.omg.CORBA.portable.Streamable
{
  public RmiDatabase value = null;

  public RmiDatabaseHolder ()
  {
  }

  public RmiDatabaseHolder (RmiDatabase initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RmiDatabaseHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RmiDatabaseHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RmiDatabaseHelper.type ();
  }

}
