package orb.rmi_corba.idl;



/**
* orb/rmi_corba/_DatabaseStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from orb/rmi_corba/Database.idl
* Monday, October 30, 2017 at 7:14:54 PM Eastern European Standard Time
*/

public class _DatabaseStub extends org.omg.CORBA.portable.ObjectImpl implements Database
{

  public String name ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_get_name", true);
                $in = _invoke ($out);
                String $result = org.omg.CORBA.WStringValueHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return name (        );
            } finally {
                _releaseReply ($in);
            }
  } // name

  public String tableNames ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_get_tableNames", true);
                $in = _invoke ($out);
                String $result = org.omg.CORBA.WStringValueHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return tableNames (        );
            } finally {
                _releaseReply ($in);
            }
  } // tableNames

  public String getTable (String arg0)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getTable", true);
                org.omg.CORBA.WStringValueHelper.write ($out, arg0);
                $in = _invoke ($out);
                String $result = org.omg.CORBA.WStringValueHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getTable (arg0        );
            } finally {
                _releaseReply ($in);
            }
  } // getTable

  public String subtract (String arg0, String arg1)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("subtract", true);
                org.omg.CORBA.WStringValueHelper.write ($out, arg0);
                org.omg.CORBA.WStringValueHelper.write ($out, arg1);
                $in = _invoke ($out);
                String $result = org.omg.CORBA.WStringValueHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return subtract (arg0, arg1        );
            } finally {
                _releaseReply ($in);
            }
  } // subtract

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "RMI:orb.rmi_corba.Database:0000000000000000"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _DatabaseStub
