package orb.rmi_corba.idl;


/**
* orb/rmi_corba/Database.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from orb/rmi_corba/Database.idl
* Monday, October 30, 2017 at 7:14:54 PM Eastern European Standard Time
*/

public interface Database extends DatabaseOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Database
