package orb.rmi_corba.idl;


/**
* orb/rmi_corba/DatabaseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from orb/rmi_corba/Database.idl
* Monday, October 30, 2017 at 7:14:54 PM Eastern European Standard Time
*/

public interface DatabaseOperations 
{
  String name();
  String tableNames();
  String getTable(String arg0);
  String subtract(String arg0, String arg1);
} // interface DatabaseOperations
