package orb.rmi_corba.idl;


/**
* orb/rmi_corba/DatabaseHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from orb/rmi_corba/Database.idl
* Monday, October 30, 2017 at 7:14:54 PM Eastern European Standard Time
*/

public final class DatabaseHolder implements org.omg.CORBA.portable.Streamable
{
  public Database value = null;

  public DatabaseHolder ()
  {
  }

  public DatabaseHolder (Database initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DatabaseHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DatabaseHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DatabaseHelper.type ();
  }

}
