package orb.rmi_corba.idl;



/**
* orb/rmi_corba/DatabaseHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from orb/rmi_corba/Database.idl
* Monday, October 30, 2017 at 7:14:54 PM Eastern European Standard Time
*/

abstract public class DatabaseHelper
{
  private static String  _id = "RMI:orb.rmi_corba.Database:0000000000000000";

  public static void insert (org.omg.CORBA.Any a, Database that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Database extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (DatabaseHelper.id (), "Database");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Database read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_DatabaseStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Database value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Database narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Database)
      return (Database)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _DatabaseStub stub = new _DatabaseStub();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Database unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Database)
      return (Database)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _DatabaseStub stub = new _DatabaseStub();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
