package orb.corba.java;

/**
* CorbaDatabasePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from orb.corba.java.CorbaDatabase.idl
* Thursday, October 26, 2017 1:23:46 PM EEST
*/

public abstract class CorbaDatabasePOA extends org.omg.PortableServer.Servant
 implements CorbaDatabaseOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getName", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // orb.corba.java.CorbaDatabase/getName
       {
         String $result = null;
         $result = this.getName ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:orb.corba.java.CorbaDatabase:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public CorbaDatabase _this() 
  {
    return CorbaDatabaseHelper.narrow(
    super._this_object());
  }

  public CorbaDatabase _this(org.omg.CORBA.ORB orb) 
  {
    return CorbaDatabaseHelper.narrow(
    super._this_object(orb));
  }


} // class CorbaDatabasePOA
