package orb.corba.java;

/**
* orb.corba.java.CorbaDatabase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from orb.corba.java.CorbaDatabase.idl
* Thursday, October 26, 2017 1:23:46 PM EEST
*/

public interface CorbaDatabase extends CorbaDatabaseOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface orb.corba.java.CorbaDatabase
