package orb.corba.java;

/**
* orb.corba.java.CorbaDatabaseHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from orb.corba.java.CorbaDatabase.idl
* Thursday, October 26, 2017 1:23:46 PM EEST
*/

public final class CorbaDatabaseHolder implements org.omg.CORBA.portable.Streamable
{
  public CorbaDatabase value = null;

  public CorbaDatabaseHolder ()
  {
  }

  public CorbaDatabaseHolder (CorbaDatabase initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CorbaDatabaseHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CorbaDatabaseHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CorbaDatabaseHelper.type ();
  }

}
