package orb.corba.java;

/**
* CorbaDatabaseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from orb.corba.java.CorbaDatabase.idl
* Thursday, October 26, 2017 1:23:46 PM EEST
*/

public interface CorbaDatabaseOperations 
{
  String getName ();
} // interface CorbaDatabaseOperations
